# GitHub workflow configuration file: Continuous Integration
#
# Copyright (C) 2021    Lucas Ritzdorf, Luca Zeuch
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

---
name: CI

on:
  push:
    paths-ignore:
      - '*.md'
      - '*.txt'
  pull_request:
    paths-ignore:
      - '*.md'
      - '*.txt'
  workflow_dispatch:

jobs:
  # Run Unit Tests via vader.vim
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install latest Vim stable
        uses: rhysd/action-setup-vim@v1
      - name: Install latest Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: v0.5.0
      - name: Run Tests
        run: make test


  # Vim script linting
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install vim-vint
        run: |
          python -m pip install --upgrade pip
          pip install vim-vint
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: run linter
        run: make lint
