# GitHub workflow configuration file: Continuous Integration
#
# Copyright (C) 2022    Lucas Ritzdorf, Luca Zeuch
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

---
name: CI

on:
  push:
    paths-ignore:
      - '*.md'
      - '*.txt'
  pull_request:
    paths-ignore:
      - '*.md'
      - '*.txt'
  workflow_dispatch:

jobs:

  test-vim:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # 8.2.2434 is the current version on Debian Bullseye and its
        # derivatives.
        version: [v8.0.0000, v8.2.0000, v8.2.2434, v9.0.0000, stable]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Vim ${{ matrix.version }}
        uses: rhysd/action-setup-vim@v1
        with:
          version: ${{ matrix.version }}

      - name: Run Vim Tests
        run: make test-vim


  test-nvim:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: [v0.5.0, v0.6.0, v0.7.0, v0.8.0, stable]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Neovim ${{ matrix.version }}
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.version }}

      - name: Run Neovim Tests
        run: make test-nvim
